# Generated by Django 5.1.6 on 2025-02-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('T', 'Tramit'), ('C', 'Chosen')], default='A', max_length=1),
        ),
    ]
