# Generated by Django 5.1.6 on 2025-02-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_category_options_alter_category_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_form',
            field=models.CharField(choices=[('P', 'PIX'), ('C', 'Card')], max_length=1),
        ),
    ]
